### ISSUE TITLE
EMPTY_SDP error ?

### ISSUE THREAD

**Issue by kakopappa** [google-home/smarthome-camerastream-webrtc#1]
Hello, 

Not sure whether provided example is out of date or I am missing something. 

Sync response:

`{"status":200,"headers":{"content-type":"application/json;charset=utf-8"},"body":{"requestId":"3975532901942190831","payload":{"agentUserId":"5fb9fc3a45e1952e0919c043","devices":[{"id":"64971cac94b0e2a6240518ad","type":"action.devices.types.CAMERA","traits":["action.devices.traits.CameraStream"],"name":{"defaultNames":["front camera"],"name":"front camera","nicknames":["front camera"]},"willReportState":true,"roomHint":"Living Room","deviceInfo":{"manufacturer":"xxx","model":"Camera","hwVersion":"1.0","swVersion":"1.0"},"attributes":{"cameraStreamSupportedProtocols":["webrtc"],"cameraStreamNeedAuthToken":true,"cameraStreamNeedDrmEncryption":false,"cameraStreamSupportsPreview":true}}]}}}`

GetCameraStream Response:

`{"status":200,"headers":{"content-type":"application/json;charset=utf-8"},"body":{"requestId":"15140443867674926092","payload":{"commands":[{"ids":["64971cac94b0e2a6240518ad"],"status":"SUCCESS","states":{"cameraStreamSignalingUrl":"https://xxxx/signaling/answer","cameraStreamProtocol":"webrtc","cameraStreamIceServers":"","cameraStreamOffer":"","cameraStreamAuthToken":""}}]}}}`

The camera says Offline and in the cloud logs, I am seeing this error. "EMPTY_SDP"

{
  "insertId": "1986k64f262ndk",
  "jsonPayload": {
    "clientUpdateLog": {
      "camerastreamProtocol": "webrtc",
      "httpRequestId": "15140443867674926092",
      "deviceType": "action.devices.types.CAMERA",
      "camerastreamExecutionUpdate": {
        "webrtcSignalingInitiationTime": "2023-07-01T04:51:15.638412952Z",
        "status": "EMPTY_SDP",
        "testPartnerFacingDebugString": "The operation couldn’t be completed. (ASTWebRTCConnectionDomain error -1015.)",
        "streamTerminationTime": "2023-07-01T04:51:15.642353057Z"
      }
    }
  },
  ....
  "receiveTimestamp": "2023-07-01T04:51:15.903721178Z"
}

Looks like cameraStreamOffer: "" is the root cause which is here: https://github.com/google-home/smarthome-camerastream-webrtc/blob/main/camerastream-done/functions/index.js#L196

i tried creating a cameraStreamOffer: based on WebRTC Validator Tool and still does not work. 

Please advise

**Comment by ghost** [comment]
Hi, 

`Looks like cameraStreamOffer: "" is the root cause which is here: https://github.com/google-home/smarthome-camerastream-webrtc/blob/main/camerastream-done/functions/index.js#L196`
In this codelab, the SH agent is not generating the offerSDP, but your Nest Display device is. The EXECUTE response only responds back with the (completed) signaling URL. This line is not the root cause of the issue outlined. 

From your `GetCameraStream` response, it looks like the `token` parameter is missing. Please make sure that’s included. Then verify (check the RealTime Database and/or web client) whether or not you are receiving the offerSDP from the Nest device and your browser is responding back with a corresponding answerSDP.

Let me know if this addresses the issue you’re experiencing. Thanks,

**Comment by kakopappa** [comment]
Hi,

I tried setting a `cameraStreamAuthToken` with a token type Bearer and still shows the same error : `"EMPTY_SDP"`

`{"status":200,"headers":{"content-type":"application/json;charset=utf-8"},"body":{"requestId":"10860344929936432175","payload":{"commands":[{"ids":["64971cac94b0e2a6240518ad"],"status":"SUCCESS","states":{"cameraStreamProtocol":"webrtc","cameraStreamSignalingUrl":"https://....../signaling/answer?token=<BearerToken>","cameraStreamIceServers":"","cameraStreamOffer":"","cameraStreamAuthToken":"<BearerToken>"}}]}}}`

BTW, I am using Google Home app for testing (it shows the camera preview) not a Nest device.. so I am not sure whether it's an issue in the app.

When I close the camera preview screen in the app i can see POST request to `cameraStreamSignalingUrl` with payload `{"action":"end"}`

**Comment by ghost** [comment]
Hi, 

The token is used as a 'session' token - to synchronise the SDPs stored in the Realtime database. Try using the following as your signaling URL (as per the [codelab](https://developers.home.google.com/codelabs/smarthome-webrtc#2)):
`https://us-central1-<project-id>.cloudfunctions.net/signaling?token='+array[1]`
Replacing `<project-id>` with the one you're using in Firebase. 

As mentioned in the [documentation](https://developers.home.google.com/cloud-to-cloud/traits/camerastream#webrtc), only the Nest Display devices and the Chromecast with Google TV are supported WebRTC devices. Currently, the Google Home App is not supported. 

Thanks,
